package com.shop.seo.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;
import java.util.UUID;

/** Singleton SEO configuration for the shop (US-SEO-01, US-SEO-04, US-SEO-05). */
@Entity
@Table(name = "shop_seo")
public class ShopSeo {

    /** Unique identifier generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** HTML {@code <title>} injected on the shop home page. */
    @Column(length = 255)
    private String seoTitle;

    /** HTML meta description injected on the shop home page. */
    @Column(length = 500)
    private String seoDescription;

    /** Comma-separated meta keywords for the shop home page. */
    @Column(length = 500)
    private String seoKeywords;

    /** Open Graph image URL used when the shop is shared on social networks. */
    @Column(name = "og_image_url", length = 500)
    private String ogImageUrl;

    /** Canonical URL for the shop home page. */
    @Column(name = "canonical_url", length = 500)
    private String canonicalUrl;

    /** Newline-separated paths to disallow in robots.txt (e.g. {@code /cart}). */
    @Column(name = "robots_disallow_paths", columnDefinition = "TEXT")
    private String robotsDisallowPaths;

    /** Change frequency hint for the sitemap (daily, weekly, monthly…). */
    @Column(name = "sitemap_changefreq", length = 20, nullable = false)
    private String sitemapChangefreq = "weekly";

    /** Whether product detail pages should be indexed by search engines. */
    @Column(name = "index_products", nullable = false)
    private boolean indexProducts = true;

    /** Whether the catalog listing page should be indexed by search engines. */
    @Column(name = "index_catalog", nullable = false)
    private boolean indexCatalog = true;

    /** Google Search Console site verification token. */
    @Column(name = "google_verification", length = 255)
    private String googleVerification;

    /** Google Analytics 4 measurement ID (G-XXXXXXXXXX). */
    @Column(name = "ga4_id", length = 50)
    private String ga4Id;

    /** Bing Webmaster Tools site verification token. */
    @Column(name = "bing_verification", length = 255)
    private String bingVerification;

    /** Timestamp when this record was first created. */
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt = LocalDateTime.now();

    /** Timestamp of the last update to this record. */
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt = LocalDateTime.now();

    /** Returns the primary key. */
    public UUID getId() { return id; }

    /** Sets the primary key. @param id the UUID */
    public void setId(UUID id) { this.id = id; }

    /** Returns the SEO title. */
    public String getSeoTitle() { return seoTitle; }

    /** Sets the SEO title. @param seoTitle the title */
    public void setSeoTitle(String seoTitle) { this.seoTitle = seoTitle; }

    /** Returns the SEO description. */
    public String getSeoDescription() { return seoDescription; }

    /** Sets the SEO description. @param seoDescription the description */
    public void setSeoDescription(String seoDescription) { this.seoDescription = seoDescription; }

    /** Returns the SEO keywords. */
    public String getSeoKeywords() { return seoKeywords; }

    /** Sets the SEO keywords. @param seoKeywords comma-separated keywords */
    public void setSeoKeywords(String seoKeywords) { this.seoKeywords = seoKeywords; }

    /** Returns the Open Graph image URL. */
    public String getOgImageUrl() { return ogImageUrl; }

    /** Sets the Open Graph image URL. @param ogImageUrl the URL */
    public void setOgImageUrl(String ogImageUrl) { this.ogImageUrl = ogImageUrl; }

    /** Returns the canonical URL. */
    public String getCanonicalUrl() { return canonicalUrl; }

    /** Sets the canonical URL. @param canonicalUrl the URL */
    public void setCanonicalUrl(String canonicalUrl) { this.canonicalUrl = canonicalUrl; }

    /** Returns the robots.txt disallow paths. */
    public String getRobotsDisallowPaths() { return robotsDisallowPaths; }

    /** Sets the robots.txt disallow paths. @param robotsDisallowPaths newline-separated paths */
    public void setRobotsDisallowPaths(String robotsDisallowPaths) { this.robotsDisallowPaths = robotsDisallowPaths; }

    /** Returns the sitemap change frequency. */
    public String getSitemapChangefreq() { return sitemapChangefreq; }

    /** Sets the sitemap change frequency. @param sitemapChangefreq the frequency string */
    public void setSitemapChangefreq(String sitemapChangefreq) { this.sitemapChangefreq = sitemapChangefreq; }

    /** Returns whether product pages are indexed. */
    public boolean isIndexProducts() { return indexProducts; }

    /** Sets whether product pages are indexed. @param indexProducts true to allow indexation */
    public void setIndexProducts(boolean indexProducts) { this.indexProducts = indexProducts; }

    /** Returns whether the catalog page is indexed. */
    public boolean isIndexCatalog() { return indexCatalog; }

    /** Sets whether the catalog page is indexed. @param indexCatalog true to allow indexation */
    public void setIndexCatalog(boolean indexCatalog) { this.indexCatalog = indexCatalog; }

    /** Returns the Google Search Console verification token. */
    public String getGoogleVerification() { return googleVerification; }

    /** Sets the Google Search Console verification token. @param googleVerification the token */
    public void setGoogleVerification(String googleVerification) { this.googleVerification = googleVerification; }

    /** Returns the Google Analytics 4 measurement ID. */
    public String getGa4Id() { return ga4Id; }

    /** Sets the Google Analytics 4 measurement ID. @param ga4Id the measurement ID */
    public void setGa4Id(String ga4Id) { this.ga4Id = ga4Id; }

    /** Returns the Bing Webmaster Tools verification token. */
    public String getBingVerification() { return bingVerification; }

    /** Sets the Bing Webmaster Tools verification token. @param bingVerification the token */
    public void setBingVerification(String bingVerification) { this.bingVerification = bingVerification; }

    /** Returns the creation timestamp. */
    public LocalDateTime getCreatedAt() { return createdAt; }

    /** Sets the creation timestamp. @param createdAt the timestamp */
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }

    /** Returns the last update timestamp. */
    public LocalDateTime getUpdatedAt() { return updatedAt; }

    /** Sets the last update timestamp. @param updatedAt the timestamp */
    public void setUpdatedAt(LocalDateTime updatedAt) { this.updatedAt = updatedAt; }
}
