package com.shop.report.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import java.math.BigDecimal;

/** A top-selling product entry in the vendor sales report (US-RPT-01). */
public record TopProduct(

        @Schema(description = "Rank of this product, starting at 1 for the best seller.")
        int rank,

        @Schema(description = "Product name snapshot from order lines.")
        String productName,

        @Schema(description = "Total quantity sold across all non-cancelled orders in the period.")
        int quantitySold,

        @Schema(description = "Total revenue generated by this product including VAT.")
        BigDecimal revenueGenerated
) {}
