package com.shop.claim.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;
import java.util.UUID;

/** A buyer claim filed against a delivered or in-transit order (US-CLM-01, US-CLM-02). */
@Entity
@Table(name = "claims")
public class Claim {

    /** Unique identifier generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** UUID of the order this claim is filed against. */
    @Column(name = "order_id", nullable = false)
    private UUID orderId;

    /** Human-readable order number snapshot for display purposes. */
    @Column(name = "order_number", nullable = false, length = 50)
    private String orderNumber;

    /** UUID of the buyer account that opened the claim. */
    @Column(name = "buyer_id", nullable = false)
    private UUID buyerId;

    /** Buyer email snapshot taken at claim creation for async notifications. */
    @Column(name = "buyer_email", nullable = false, length = 255)
    private String buyerEmail;

    /** UUID of the vendor account responsible for this claim. */
    @Column(name = "vendor_id", nullable = false)
    private UUID vendorId;

    /** Vendor email snapshot taken at claim creation for async notifications. */
    @Column(name = "vendor_email", nullable = false, length = 255)
    private String vendorEmail;

    /** Reason selected by the buyer when opening the claim. */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 30)
    private ClaimReason reason;

    /** Free-text description provided by the buyer. */
    @Column(nullable = false, columnDefinition = "TEXT")
    private String message;

    /** Current lifecycle status of the claim. */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private ClaimStatus status;

    /** Vendor decision — set when the claim transitions to CLOSED. */
    @Enumerated(EnumType.STRING)
    @Column(length = 20)
    private ClaimDecision decision;

    /** Timestamp when the claim was opened. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /** Timestamp of the last status change. */
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    /** Sets timestamps on first persist. */
    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
    }

    /** Refreshes updatedAt on every merge. */
    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }

    /** @return the claim UUID */
    public UUID getId() { return id; }

    /** @return the order UUID this claim is filed against */
    public UUID getOrderId() { return orderId; }

    /** @param orderId the order UUID */
    public void setOrderId(UUID orderId) { this.orderId = orderId; }

    /** @return the human-readable order number snapshot */
    public String getOrderNumber() { return orderNumber; }

    /** @param orderNumber the human-readable order number snapshot */
    public void setOrderNumber(String orderNumber) { this.orderNumber = orderNumber; }

    /** @return the buyer account UUID */
    public UUID getBuyerId() { return buyerId; }

    /** @param buyerId the buyer account UUID */
    public void setBuyerId(UUID buyerId) { this.buyerId = buyerId; }

    /** @return the buyer email snapshot */
    public String getBuyerEmail() { return buyerEmail; }

    /** @param buyerEmail the buyer email snapshot */
    public void setBuyerEmail(String buyerEmail) { this.buyerEmail = buyerEmail; }

    /** @return the vendor account UUID */
    public UUID getVendorId() { return vendorId; }

    /** @param vendorId the vendor account UUID */
    public void setVendorId(UUID vendorId) { this.vendorId = vendorId; }

    /** @return the vendor email snapshot */
    public String getVendorEmail() { return vendorEmail; }

    /** @param vendorEmail the vendor email snapshot */
    public void setVendorEmail(String vendorEmail) { this.vendorEmail = vendorEmail; }

    /** @return the claim reason selected by the buyer */
    public ClaimReason getReason() { return reason; }

    /** @param reason the claim reason */
    public void setReason(ClaimReason reason) { this.reason = reason; }

    /** @return the free-text message from the buyer */
    public String getMessage() { return message; }

    /** @param message the free-text message */
    public void setMessage(String message) { this.message = message; }

    /** @return the current claim status */
    public ClaimStatus getStatus() { return status; }

    /** @param status the new claim status */
    public void setStatus(ClaimStatus status) { this.status = status; }

    /** @return the vendor decision, or {@code null} if still open */
    public ClaimDecision getDecision() { return decision; }

    /** @param decision the vendor decision */
    public void setDecision(ClaimDecision decision) { this.decision = decision; }

    /** @return the timestamp when the claim was opened */
    public LocalDateTime getCreatedAt() { return createdAt; }

    /** @return the timestamp of the last status change */
    public LocalDateTime getUpdatedAt() { return updatedAt; }
}
