package com.shop.audit.entity;

/** Security-relevant event types recorded in the audit log (SEC-LOG-001 / CPA-13). */
public enum AuditEventType {
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    ACCOUNT_LOCKED,
    REGISTRATION,
    ACCOUNT_ACTIVATED,
    PASSWORD_CHANGED,
    ACCOUNT_SUSPENDED,
    ACCOUNT_REACTIVATED,
    ACCOUNT_DELETED,
    ACCOUNT_CREATED,
    RESEND_ACTIVATION,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET,
    MFA_ENABLED,
    MFA_LOGIN_SUCCESS,
    MFA_LOGIN_FAILURE,
    PASSWORD_REVOKED,
    MARKETING_CONSENT_EXPORT
}
