package com.shop.order.entity;

import jakarta.persistence.*;
import java.math.BigDecimal;
import java.util.UUID;

/** A product line snapshotted from the cart at order creation (US-ORD-01). */
@Entity
@Table(name = "order_lines")
public class OrderLine {

    /** Unique identifier generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** The order this line belongs to. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "order_id", nullable = false)
    private Order order;

    /** UUID of the original product (nullable — product may be deleted after ordering). */
    @Column(name = "product_id")
    private UUID productId;

    /** Product name snapshot — preserved even if the product is later deleted. */
    @Column(name = "product_name", nullable = false, length = 200)
    private String productName;

    /** Pre-tax unit price snapshot at order creation time. */
    @Column(name = "unit_price_excl_tax", nullable = false, precision = 10, scale = 2)
    private BigDecimal unitPriceExclTax;

    /** Unit price including VAT snapshot. */
    @Column(name = "unit_price_ttc", nullable = false, precision = 10, scale = 2)
    private BigDecimal unitPriceTtc;

    /** Quantity ordered. */
    @Column(nullable = false)
    private int quantity;

    /** Line total including VAT (unitPriceTtc × quantity). */
    @Column(name = "line_total_ttc", nullable = false, precision = 10, scale = 2)
    private BigDecimal lineTotalTtc;

    /** @return the line UUID */
    public UUID getId() { return id; }

    /** @return the parent order */
    public Order getOrder() { return order; }

    /** @param order the parent order */
    public void setOrder(Order order) { this.order = order; }

    /** @return the product UUID, or {@code null} if the product was deleted */
    public UUID getProductId() { return productId; }

    /** @param productId the product UUID */
    public void setProductId(UUID productId) { this.productId = productId; }

    /** @return the product name snapshot */
    public String getProductName() { return productName; }

    /** @param productName the product name snapshot */
    public void setProductName(String productName) { this.productName = productName; }

    /** @return the pre-tax unit price snapshot */
    public BigDecimal getUnitPriceExclTax() { return unitPriceExclTax; }

    /** @param unitPriceExclTax the pre-tax unit price snapshot */
    public void setUnitPriceExclTax(BigDecimal unitPriceExclTax) { this.unitPriceExclTax = unitPriceExclTax; }

    /** @return the unit price including VAT snapshot */
    public BigDecimal getUnitPriceTtc() { return unitPriceTtc; }

    /** @param unitPriceTtc the unit price including VAT snapshot */
    public void setUnitPriceTtc(BigDecimal unitPriceTtc) { this.unitPriceTtc = unitPriceTtc; }

    /** @return the quantity ordered */
    public int getQuantity() { return quantity; }

    /** @param quantity the quantity ordered */
    public void setQuantity(int quantity) { this.quantity = quantity; }

    /** @return the line total including VAT */
    public BigDecimal getLineTotalTtc() { return lineTotalTtc; }

    /** @param lineTotalTtc the line total including VAT */
    public void setLineTotalTtc(BigDecimal lineTotalTtc) { this.lineTotalTtc = lineTotalTtc; }
}
