package com.shop.order.entity;

import com.shop.account.entity.DeliveryAddress;
import jakarta.persistence.*;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/** A buyer order created at checkout (US-ORD-01..05). */
@Entity
@Table(name = "orders")
public class Order {

    /** Unique identifier generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Human-readable order reference (e.g. ORD-20240118-A3F7). */
    @Column(name = "order_number", nullable = false, unique = true, length = 50)
    private String orderNumber;

    /** UUID of the buyer account that placed this order. */
    @Column(name = "buyer_id", nullable = false)
    private UUID buyerId;

    /** UUID of the carrier selected at checkout. */
    @Column(name = "carrier_id", nullable = false)
    private UUID carrierId;

    /** Carrier name snapshot — independent of later carrier edits. */
    @Column(name = "carrier_name", nullable = false, length = 100)
    private String carrierName;

    /** Carrier tracking URL snapshot. */
    @Column(name = "carrier_tracking_url", nullable = false, length = 500)
    private String carrierTrackingUrl;

    /** Delivery address selected by the buyer at checkout (US-PRF-03). */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "delivery_address_id", nullable = false)
    private DeliveryAddress deliveryAddress;

    /** Payment method chosen at checkout. */
    @Enumerated(EnumType.STRING)
    @Column(name = "payment_method", nullable = false, length = 20)
    private PaymentMethod paymentMethod;

    /** Current lifecycle status. */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 50)
    private OrderStatus status;

    /** Grand total including 20% VAT. */
    @Column(name = "total_amount_ttc", nullable = false, precision = 10, scale = 2)
    private BigDecimal totalAmountTtc;

    /** Stripe PaymentIntent ID — set for CARD orders, null for WIRE_TRANSFER. */
    @Column(name = "stripe_payment_intent_id", length = 100)
    private String stripePaymentIntentId;

    /** Buyer IBAN collected when the buyer requests a wire transfer refund. */
    @Column(name = "buyer_iban", length = 34)
    private String buyerIban;

    /** Tracking number supplied by the vendor at shipment (US-EXP-01). */
    @Column(name = "tracking_number", length = 100)
    private String trackingNumber;

    /** Reason provided by the buyer when requesting post-shipment cancellation (US-CAN-06). */
    @Column(name = "cancellation_reason", length = 500)
    private String cancellationReason;

    /** Line items snapshotted from the cart at order creation. */
    @OneToMany(mappedBy = "order", cascade = CascadeType.ALL, orphanRemoval = true)
    @OrderBy("id ASC")
    private List<OrderLine> lines = new ArrayList<>();

    /** Timestamp when the order was placed. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /** Timestamp of the last status change. */
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    /** Sets timestamps on first persist. */
    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
    }

    /** Refreshes updatedAt on every merge. */
    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }

    /** @return the order UUID */
    public UUID getId() { return id; }

    /** @return the human-readable order number */
    public String getOrderNumber() { return orderNumber; }

    /** @param orderNumber the human-readable order number */
    public void setOrderNumber(String orderNumber) { this.orderNumber = orderNumber; }

    /** @return the buyer account UUID */
    public UUID getBuyerId() { return buyerId; }

    /** @param buyerId the buyer account UUID */
    public void setBuyerId(UUID buyerId) { this.buyerId = buyerId; }

    /** @return the carrier UUID */
    public UUID getCarrierId() { return carrierId; }

    /** @param carrierId the carrier UUID */
    public void setCarrierId(UUID carrierId) { this.carrierId = carrierId; }

    /** @return the carrier name snapshot */
    public String getCarrierName() { return carrierName; }

    /** @param carrierName the carrier name snapshot */
    public void setCarrierName(String carrierName) { this.carrierName = carrierName; }

    /** @return the carrier tracking URL snapshot */
    public String getCarrierTrackingUrl() { return carrierTrackingUrl; }

    /** @param carrierTrackingUrl the carrier tracking URL snapshot */
    public void setCarrierTrackingUrl(String carrierTrackingUrl) { this.carrierTrackingUrl = carrierTrackingUrl; }

    /** @return the delivery address entity selected at checkout */
    public DeliveryAddress getDeliveryAddress() { return deliveryAddress; }

    /** @param deliveryAddress the delivery address selected at checkout */
    public void setDeliveryAddress(DeliveryAddress deliveryAddress) { this.deliveryAddress = deliveryAddress; }

    /** @return the chosen payment method */
    public PaymentMethod getPaymentMethod() { return paymentMethod; }

    /** @param paymentMethod the chosen payment method */
    public void setPaymentMethod(PaymentMethod paymentMethod) { this.paymentMethod = paymentMethod; }

    /** @return the current order status */
    public OrderStatus getStatus() { return status; }

    /** @param status the new order status */
    public void setStatus(OrderStatus status) { this.status = status; }

    /** @return the grand total including VAT */
    public BigDecimal getTotalAmountTtc() { return totalAmountTtc; }

    /** @param totalAmountTtc the grand total including VAT */
    public void setTotalAmountTtc(BigDecimal totalAmountTtc) { this.totalAmountTtc = totalAmountTtc; }

    /** @return the Stripe PaymentIntent ID, or {@code null} for wire transfers */
    public String getStripePaymentIntentId() { return stripePaymentIntentId; }

    /** @param stripePaymentIntentId the Stripe PaymentIntent ID */
    public void setStripePaymentIntentId(String stripePaymentIntentId) { this.stripePaymentIntentId = stripePaymentIntentId; }

    /** @return the buyer's IBAN for wire refunds, or {@code null} if not yet provided */
    public String getBuyerIban() { return buyerIban; }

    /** @param buyerIban the buyer's IBAN */
    public void setBuyerIban(String buyerIban) { this.buyerIban = buyerIban; }

    /** @return the shipment tracking number, or {@code null} if not yet shipped */
    public String getTrackingNumber() { return trackingNumber; }

    /** @param trackingNumber the shipment tracking number */
    public void setTrackingNumber(String trackingNumber) { this.trackingNumber = trackingNumber; }

    /** @return the buyer's cancellation reason, or {@code null} if not yet requested */
    public String getCancellationReason() { return cancellationReason; }

    /** @param cancellationReason the reason provided by the buyer for the post-shipment cancellation request */
    public void setCancellationReason(String cancellationReason) { this.cancellationReason = cancellationReason; }

    /** @return the ordered list of line items */
    public List<OrderLine> getLines() { return lines; }

    /** @return the order placement timestamp */
    public LocalDateTime getCreatedAt() { return createdAt; }

    /** @return the last status-change timestamp */
    public LocalDateTime getUpdatedAt() { return updatedAt; }
}
