@startuml pa-deployment-en
skinparam defaultFontSize 11
skinparam shadowing false
skinparam ArrowColor #2E75B6
skinparam nodeBorderColor #2E75B6
skinparam nodeBackgroundColor #E8F4FD
skinparam databaseBorderColor #2E75B6
skinparam databaseBackgroundColor #E8F4FD
skinparam rectangleBorderColor #2E75B6
skinparam rectangleBackgroundColor #EEF4FB

left to right direction

actor "Buyer"         as Buyer
actor "Vendor"        as Vendor
actor "Administrator" as Admin

node "Container\nbuyer-portal\n(React · Nginx)" as FrontB
node "Container\nvendor-backoffice\n(React · Nginx)" as FrontV
node "Container\nadmin-console\n(React · Nginx)" as FrontA
node "Container\nbackend\n(Spring Boot)" as API
database "Container\nPostgreSQL 16" as DB
database "Container\nRedis 7" as Redis
rectangle "Stripe API\n(external)" as Stripe
rectangle "SendGrid\n(external)" as SMTP

Buyer  --> FrontB : HTTPS
Vendor --> FrontV : HTTPS
Admin  --> FrontA : HTTPS

FrontB --> API : TLS
FrontV --> API : TLS
FrontA --> API : TLS

API --> DB    : SQL (JPA / Flyway)
API --> Redis : cache · sessions
API --> Stripe : HTTPS
API --> SMTP   : HTTPS

@enduml
