FROM node:20
RUN apt-get update && apt-get install -y openssh-server nginx \
    && mkdir /var/run/sshd \
    && echo 'root:dev' | chpasswd \
    && sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
COPY nginx.dev.conf /etc/nginx/nginx.conf
WORKDIR /workspace
EXPOSE 22 80
CMD sh -c "nginx && exec /usr/sbin/sshd -D"
