package com.shop.catalog.entity;

import jakarta.persistence.*;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/** A product offered by a vendor in the catalog (US-CAT-01 to US-CAT-04). */
@Entity
@Table(name = "products")
public class Product {

    /** Unique identifier generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Display name of the product. */
    @Column(nullable = false, length = 200)
    private String name;

    /** Optional detailed description. */
    @Column(columnDefinition = "TEXT")
    private String description;

    /** Pre-tax unit price in euros. */
    @Column(name = "price_excl_tax", nullable = false, precision = 10, scale = 2)
    private BigDecimal priceExclTax;

    /** Optional product category — represents the physical product type (poster, carte…). */
    @Column(length = 100)
    private String category;

    /** Optional product theme or occasion (paysage, naissance, vacances…). */
    @Column(length = 100)
    private String theme;

    /** Current available quantity in stock. */
    @Column(nullable = false)
    private int quantity = 0;

    /** Stock quantity below which a stock alert is triggered (US-CAT-05). */
    @Column(name = "stock_alert_threshold", nullable = false)
    private int stockAlertThreshold = 0;

    /** Current lifecycle status of the product. */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private ProductStatus status = ProductStatus.PUBLISHED;

    /** Ordered list of photos associated with this product. */
    @OneToMany(mappedBy = "product", cascade = CascadeType.ALL, orphanRemoval = true)
    @OrderBy("sortOrder ASC")
    private List<ProductPhoto> photos = new ArrayList<>();

    /** Timestamp when the product was first created. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /** Timestamp of the last update to any product field. */
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    /** Sets creation and update timestamps before first persist. */
    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
    }

    /** Refreshes the update timestamp on every merge. */
    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }

    /** @return the product UUID */
    public UUID getId() { return id; }

    /** @return the product display name */
    public String getName() { return name; }

    /** @param name the product display name */
    public void setName(String name) { this.name = name; }

    /** @return the product description, or {@code null} if not set */
    public String getDescription() { return description; }

    /** @param description the product description */
    public void setDescription(String description) { this.description = description; }

    /** @return the pre-tax unit price */
    public BigDecimal getPriceExclTax() { return priceExclTax; }

    /** @param priceExclTax the pre-tax unit price */
    public void setPriceExclTax(BigDecimal priceExclTax) { this.priceExclTax = priceExclTax; }

    /** @return the product category (type), or {@code null} if not set */
    public String getCategory() { return category; }

    /** @param category the product category (type) */
    public void setCategory(String category) { this.category = category; }

    /** @return the product theme or occasion, or {@code null} if not set */
    public String getTheme() { return theme; }

    /** @param theme the product theme or occasion */
    public void setTheme(String theme) { this.theme = theme; }

    /** @return the current available quantity */
    public int getQuantity() { return quantity; }

    /** @param quantity the current available quantity */
    public void setQuantity(int quantity) { this.quantity = quantity; }

    /** @return the stock alert threshold */
    public int getStockAlertThreshold() { return stockAlertThreshold; }

    /** @param stockAlertThreshold the stock alert threshold */
    public void setStockAlertThreshold(int stockAlertThreshold) { this.stockAlertThreshold = stockAlertThreshold; }

    /** @return the lifecycle status */
    public ProductStatus getStatus() { return status; }

    /** @param status the lifecycle status */
    public void setStatus(ProductStatus status) { this.status = status; }

    /** @return the ordered list of photos */
    public List<ProductPhoto> getPhotos() { return photos; }

    /** @return the creation timestamp */
    public LocalDateTime getCreatedAt() { return createdAt; }

    /** @return the last-updated timestamp */
    public LocalDateTime getUpdatedAt() { return updatedAt; }
}
