package com.shop.catalog.entity;

import jakarta.persistence.*;
import java.util.UUID;

/** A photo URL associated with a product (US-CAT-01). */
@Entity
@Table(name = "product_photos")
public class ProductPhoto {

    /** Unique identifier generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** The product this photo belongs to. */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "product_id", nullable = false)
    private Product product;

    /** Publicly accessible URL of the photo. */
    @Column(nullable = false, length = 500)
    private String url;

    /** Display order among the product's photos (0 = first). */
    @Column(name = "sort_order", nullable = false)
    private int sortOrder = 0;

    /** @return the photo UUID */
    public UUID getId() { return id; }

    /** @return the owning product */
    public Product getProduct() { return product; }

    /** @param product the owning product */
    public void setProduct(Product product) { this.product = product; }

    /** @return the photo URL */
    public String getUrl() { return url; }

    /** @param url the photo URL */
    public void setUrl(String url) { this.url = url; }

    /** @return the display sort order */
    public int getSortOrder() { return sortOrder; }

    /** @param sortOrder the display sort order */
    public void setSortOrder(int sortOrder) { this.sortOrder = sortOrder; }
}
