package com.shop.catalog.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;
import java.util.UUID;

/** Records a stock-below-threshold event for a vendor product (US-CAT-05). */
@Entity
@Table(name = "stock_alerts")
public class StockAlert {

    /** Unique identifier generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** The product whose stock crossed the alert threshold. */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "product_id", nullable = false)
    private Product product;

    /** Timestamp when the threshold was crossed. */
    @Column(name = "triggered_at", nullable = false)
    private LocalDateTime triggeredAt;

    /** Whether the vendor has acknowledged this alert. */
    @Column(nullable = false)
    private boolean acknowledged = false;

    /** @return the alert UUID */
    public UUID getId() { return id; }

    /** @return the product whose stock triggered this alert */
    public Product getProduct() { return product; }

    /** @param product the product whose stock triggered this alert */
    public void setProduct(Product product) { this.product = product; }

    /** @return the timestamp when the threshold was crossed */
    public LocalDateTime getTriggeredAt() { return triggeredAt; }

    /** @param triggeredAt the timestamp when the threshold was crossed */
    public void setTriggeredAt(LocalDateTime triggeredAt) { this.triggeredAt = triggeredAt; }

    /** @return {@code true} if the vendor has acknowledged this alert */
    public boolean isAcknowledged() { return acknowledged; }

    /** @param acknowledged {@code true} to mark as acknowledged */
    public void setAcknowledged(boolean acknowledged) { this.acknowledged = acknowledged; }
}
