package com.shop.carrier.entity;

import jakarta.persistence.*;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/** Shipping carrier available on the platform (US-ADM-06). */
@Entity
@Table(name = "carriers")
public class Carrier {

    /** Unique identifier generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Carrier display name. */
    @Column(nullable = false, length = 100)
    private String name;

    /** Parcel tracking URL exposed to buyers. */
    @Column(name = "tracking_url", nullable = false, length = 500)
    private String trackingUrl;

    /** Whether the carrier is currently active and available to vendors. */
    @Column(nullable = false)
    private boolean active = true;

    /** ISO 3166-1 alpha-2 codes of supported Eurozone countries (CS-04). */
    @ElementCollection
    @CollectionTable(name = "carrier_countries", joinColumns = @JoinColumn(name = "carrier_id"))
    @Column(name = "country_code")
    private List<String> supportedCountries = new ArrayList<>();

    /** Timestamp when the carrier was created. */
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    /** @return carrier UUID */
    public UUID getId() { return id; }

    /** @return carrier display name */
    public String getName() { return name; }

    /** @param name carrier display name */
    public void setName(String name) { this.name = name; }

    /** @return parcel tracking URL */
    public String getTrackingUrl() { return trackingUrl; }

    /** @param trackingUrl parcel tracking URL */
    public void setTrackingUrl(String trackingUrl) { this.trackingUrl = trackingUrl; }

    /** @return {@code true} if active */
    public boolean isActive() { return active; }

    /** @param active {@code true} to activate */
    public void setActive(boolean active) { this.active = active; }

    /** @return mutable list of ISO 3166-1 alpha-2 codes */
    public List<String> getSupportedCountries() { return supportedCountries; }

    /** @param supportedCountries list of ISO 3166-1 alpha-2 codes */
    public void setSupportedCountries(List<String> supportedCountries) {
        this.supportedCountries = supportedCountries;
    }

    /** @return creation date-time */
    public LocalDateTime getCreatedAt() { return createdAt; }

    /** @param createdAt creation date-time */
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }
}
