package com.shop.account.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;
import java.util.UUID;

/** Platform account — buyer, vendor, or admin. */
@Entity
@Table(name = "accounts")
public class Account {

    /** Unique identifier generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Email address, unique across the platform. */
    @Column(nullable = false, unique = true, length = 255)
    private String email;

    /** BCrypt-hashed password — null until the account activates via email link. */
    @Column(nullable = true, name = "password_hash", length = 255)
    private String passwordHash;

    /** Given name of the account holder. */
    @Column(name = "first_name", nullable = false, length = 100)
    private String firstName;

    /** Family name of the account holder. */
    @Column(name = "last_name", nullable = false, length = 100)
    private String lastName;

    /** Role determining access level on the platform. */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private AccountRole role;

    /** Current lifecycle status of the account. */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private AccountStatus status;

    /** Preferred language for notification emails (CS-10). */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 2)
    private AccountLanguage language = AccountLanguage.FR;

    /** Whether the account must change its password on next login. */
    @Column(name = "must_change_password", nullable = false)
    private boolean mustChangePassword = false;

    /** Timestamp when the account was created. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /** Phone number — optional contact info (UCSA-02). */
    @Column(length = 20)
    private String phone;

    /** Street address line — default shipping address (UCSA-02). */
    @Column(name = "address_line", length = 255)
    private String addressLine;

    /** City — default shipping address (UCSA-02). */
    @Column(length = 100)
    private String city;

    /** Postal code — default shipping address (UCSA-02). */
    @Column(name = "postal_code", length = 20)
    private String postalCode;

    /** ISO 3166-1 alpha-2 country code restricted to euro zone (CS-04 / UCSA-02). */
    @Column(name = "country_code", length = 2)
    private String countryCode;

    /** Sets creation timestamp before first persist. */
    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
    }

    /** @return the account UUID */
    public UUID getId() { return id; }

    /** @return the email address */
    public String getEmail() { return email; }

    /** @param email the email to set */
    public void setEmail(String email) { this.email = email; }

    /** @return the hashed password */
    public String getPasswordHash() { return passwordHash; }

    /** @param passwordHash the hashed password to set */
    public void setPasswordHash(String passwordHash) { this.passwordHash = passwordHash; }

    /** @return the first name */
    public String getFirstName() { return firstName; }

    /** @param firstName the first name to set */
    public void setFirstName(String firstName) { this.firstName = firstName; }

    /** @return the last name */
    public String getLastName() { return lastName; }

    /** @param lastName the last name to set */
    public void setLastName(String lastName) { this.lastName = lastName; }

    /** @return the account role */
    public AccountRole getRole() { return role; }

    /** @param role the role to set */
    public void setRole(AccountRole role) { this.role = role; }

    /** @return the account status */
    public AccountStatus getStatus() { return status; }

    /** @param status the status to set */
    public void setStatus(AccountStatus status) { this.status = status; }

    /** @return the preferred notification language */
    public AccountLanguage getLanguage() { return language; }

    /** @param language the notification language to set */
    public void setLanguage(AccountLanguage language) { this.language = language; }

    /** @return {@code true} if the account must change its password on next login */
    public boolean isMustChangePassword() { return mustChangePassword; }

    /** @param mustChangePassword whether a password change is required on next login */
    public void setMustChangePassword(boolean mustChangePassword) { this.mustChangePassword = mustChangePassword; }

    /** @return the creation timestamp */
    public LocalDateTime getCreatedAt() { return createdAt; }

    /** @return the phone number, or {@code null} if not set */
    public String getPhone() { return phone; }

    /** @param phone the phone number to set */
    public void setPhone(String phone) { this.phone = phone; }

    /** @return the street address line, or {@code null} if not set */
    public String getAddressLine() { return addressLine; }

    /** @param addressLine the street address line to set */
    public void setAddressLine(String addressLine) { this.addressLine = addressLine; }

    /** @return the city, or {@code null} if not set */
    public String getCity() { return city; }

    /** @param city the city to set */
    public void setCity(String city) { this.city = city; }

    /** @return the postal code, or {@code null} if not set */
    public String getPostalCode() { return postalCode; }

    /** @param postalCode the postal code to set */
    public void setPostalCode(String postalCode) { this.postalCode = postalCode; }

    /** @return the ISO 3166-1 alpha-2 country code, or {@code null} if not set */
    public String getCountryCode() { return countryCode; }

    /** @param countryCode the ISO 3166-1 alpha-2 country code to set */
    public void setCountryCode(String countryCode) { this.countryCode = countryCode; }
}
