package com.shop.account.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;
import java.util.UUID;

/** Platform account — buyer, vendor, or admin. */
@Entity
@Table(name = "accounts")
public class Account {

    /** Unique identifier generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Email address, unique across the platform. */
    @Column(nullable = false, unique = true, length = 255)
    private String email;

    /** BCrypt-hashed password — null until the account activates via email link. */
    @Column(nullable = true, name = "password_hash", length = 255)
    private String passwordHash;

    /** Given name of the account holder. */
    @Column(name = "first_name", nullable = false, length = 100)
    private String firstName;

    /** Family name of the account holder. */
    @Column(name = "last_name", nullable = false, length = 100)
    private String lastName;

    /** Role determining access level on the platform. */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private AccountRole role;

    /** Current lifecycle status of the account. */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private AccountStatus status;

    /** Timestamp when the account was created. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /** Sets creation timestamp before first persist. */
    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
    }

    /** @return the account UUID */
    public UUID getId() { return id; }

    /** @return the email address */
    public String getEmail() { return email; }

    /** @param email the email to set */
    public void setEmail(String email) { this.email = email; }

    /** @return the hashed password */
    public String getPasswordHash() { return passwordHash; }

    /** @param passwordHash the hashed password to set */
    public void setPasswordHash(String passwordHash) { this.passwordHash = passwordHash; }

    /** @return the first name */
    public String getFirstName() { return firstName; }

    /** @param firstName the first name to set */
    public void setFirstName(String firstName) { this.firstName = firstName; }

    /** @return the last name */
    public String getLastName() { return lastName; }

    /** @param lastName the last name to set */
    public void setLastName(String lastName) { this.lastName = lastName; }

    /** @return the account role */
    public AccountRole getRole() { return role; }

    /** @param role the role to set */
    public void setRole(AccountRole role) { this.role = role; }

    /** @return the account status */
    public AccountStatus getStatus() { return status; }

    /** @param status the status to set */
    public void setStatus(AccountStatus status) { this.status = status; }

    /** @return the creation timestamp */
    public LocalDateTime getCreatedAt() { return createdAt; }
}
