package com.shop.account.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;
import java.util.UUID;

/** A buyer's saved delivery address (US-PRF-03). Soft-deleted to preserve order FK integrity. */
@Entity
@Table(name = "delivery_address")
public class DeliveryAddress {

    /** Unique identifier generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** Buyer account that owns this address. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "account_id", nullable = false)
    private Account account;

    /** Short label chosen by the buyer (e.g. "Home", "Office"). */
    @Column(nullable = false, length = 100)
    private String label;

    /** Name of the person who will receive the parcel — may differ from the buyer's account name. */
    @Column(name = "recipient_name", nullable = false, length = 100)
    private String recipientName;

    /** Street address line. */
    @Column(name = "address_line", nullable = false, length = 255)
    private String addressLine;

    /** City. */
    @Column(nullable = false, length = 100)
    private String city;

    /** Postal code. */
    @Column(name = "postal_code", nullable = false, length = 20)
    private String postalCode;

    /** ISO 3166-1 alpha-2 country code, restricted to Eurozone (CS-04). */
    @Column(name = "country_code", nullable = false, length = 2)
    private String countryCode;

    /** Whether this address is the buyer's default delivery address. */
    @Column(name = "is_default", nullable = false)
    private boolean isDefault = false;

    /**
     * Soft-delete flag — true means the address is hidden from the buyer but kept in the
     * database to preserve referential integrity with past orders.
     */
    @Column(nullable = false)
    private boolean deleted = false;

    /** Timestamp when the address was created. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /** Timestamp of the last modification. */
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    /** Sets timestamps on first persist. */
    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
    }

    /** Refreshes updatedAt on every merge. */
    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }

    /** @return the address UUID */
    public UUID getId() { return id; }

    /** @return the owner account */
    public Account getAccount() { return account; }

    /** @param account the owner account */
    public void setAccount(Account account) { this.account = account; }

    /** @return the address label */
    public String getLabel() { return label; }

    /** @param label the address label */
    public void setLabel(String label) { this.label = label; }

    /** @return the recipient name for the parcel */
    public String getRecipientName() { return recipientName; }

    /** @param recipientName the recipient name for the parcel */
    public void setRecipientName(String recipientName) { this.recipientName = recipientName; }

    /** @return the street address line */
    public String getAddressLine() { return addressLine; }

    /** @param addressLine the street address line */
    public void setAddressLine(String addressLine) { this.addressLine = addressLine; }

    /** @return the city */
    public String getCity() { return city; }

    /** @param city the city */
    public void setCity(String city) { this.city = city; }

    /** @return the postal code */
    public String getPostalCode() { return postalCode; }

    /** @param postalCode the postal code */
    public void setPostalCode(String postalCode) { this.postalCode = postalCode; }

    /** @return the ISO alpha-2 country code */
    public String getCountryCode() { return countryCode; }

    /** @param countryCode the ISO alpha-2 country code */
    public void setCountryCode(String countryCode) { this.countryCode = countryCode; }

    /** @return true if this is the buyer's default address */
    public boolean isDefault() { return isDefault; }

    /** @param isDefault true to mark this address as the default */
    public void setDefault(boolean isDefault) { this.isDefault = isDefault; }

    /** @return true if the address has been soft-deleted */
    public boolean isDeleted() { return deleted; }

    /** @param deleted true to soft-delete this address */
    public void setDeleted(boolean deleted) { this.deleted = deleted; }

    /** @return the creation timestamp */
    public LocalDateTime getCreatedAt() { return createdAt; }

    /** @return the last-updated timestamp */
    public LocalDateTime getUpdatedAt() { return updatedAt; }
}
