FROM maven:3.9-eclipse-temurin-21
RUN apt-get update && apt-get install -y openssh-server \
    && mkdir /var/run/sshd \
    && echo 'root:dev' | chpasswd \
    && sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
WORKDIR /workspace
EXPOSE 22 8080
CMD ["/usr/sbin/sshd", "-D"]
