package com.shop.cart.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/** Persistent shopping cart, one per buyer (US-CRT-01, US-CRT-02). */
@Entity
@Table(name = "cart")
public class Cart {

    /** Unique identifier generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** UUID of the buyer account that owns this cart. */
    @Column(name = "buyer_id", nullable = false, unique = true)
    private UUID buyerId;

    /** Line items currently in this cart. */
    @OneToMany(mappedBy = "cart", cascade = CascadeType.ALL, orphanRemoval = true)
    @OrderBy("createdAt ASC")
    private List<CartItem> items = new ArrayList<>();

    /** Timestamp when the cart was first created. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /** Timestamp of the last modification to this cart or any of its items. */
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    /** Sets creation and update timestamps before first persist. */
    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
    }

    /** Refreshes the update timestamp on every merge. */
    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }

    /** @return the cart UUID */
    public UUID getId() { return id; }

    /** @return the buyer account UUID */
    public UUID getBuyerId() { return buyerId; }

    /** @param buyerId the buyer account UUID */
    public void setBuyerId(UUID buyerId) { this.buyerId = buyerId; }

    /** @return the ordered list of line items */
    public List<CartItem> getItems() { return items; }

    /** @return the creation timestamp */
    public LocalDateTime getCreatedAt() { return createdAt; }

    /** @return the last-updated timestamp */
    public LocalDateTime getUpdatedAt() { return updatedAt; }

    /** @param updatedAt the new last-updated timestamp */
    public void setUpdatedAt(LocalDateTime updatedAt) { this.updatedAt = updatedAt; }
}
