package com.shop.cart.entity;

import com.shop.catalog.entity.Product;
import jakarta.persistence.*;
import java.time.LocalDateTime;
import java.util.UUID;

/** A single product line within a buyer's cart (US-CRT-01). */
@Entity
@Table(name = "cart_item")
public class CartItem {

    /** Unique identifier generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** The cart this item belongs to. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "cart_id", nullable = false)
    private Cart cart;

    /** The product referenced by this line item. */
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "product_id", nullable = false)
    private Product product;

    /** Number of units of the product in this line. */
    @Column(nullable = false)
    private int quantity;

    /** Timestamp when this item was first added to the cart. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /** Timestamp of the last quantity update for this item. */
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    /** Sets creation and update timestamps before first persist. */
    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
    }

    /** Refreshes the update timestamp on every merge. */
    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }

    /** @return the item UUID */
    public UUID getId() { return id; }

    /** @return the parent cart */
    public Cart getCart() { return cart; }

    /** @param cart the parent cart */
    public void setCart(Cart cart) { this.cart = cart; }

    /** @return the referenced product */
    public Product getProduct() { return product; }

    /** @param product the referenced product */
    public void setProduct(Product product) { this.product = product; }

    /** @return the quantity of the product in this line */
    public int getQuantity() { return quantity; }

    /** @param quantity the quantity of the product in this line */
    public void setQuantity(int quantity) { this.quantity = quantity; }

    /** @return the creation timestamp */
    public LocalDateTime getCreatedAt() { return createdAt; }

    /** @return the last-updated timestamp */
    public LocalDateTime getUpdatedAt() { return updatedAt; }
}
