package com.shop.announcement.entity;

import com.shop.account.entity.Account;
import jakarta.persistence.*;
import java.time.LocalDateTime;
import java.util.UUID;

/** A scrolling announcement displayed on the buyer portal home page (US-ANN-01 / FS-V11). */
@Entity
@Table(name = "announcements")
public class Announcement {

    /** Unique identifier generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /** The vendor who owns this announcement. */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "vendor_id", nullable = false)
    private Account vendor;

    /** Whether this announcement is text-only, image-only, or both. */
    @Enumerated(EnumType.STRING)
    @Column(name = "content_type", nullable = false, length = 20)
    private AnnouncementContentType contentType;

    /** Text body of the announcement (required for TEXT and BOTH types). */
    @Column(name = "text_content", length = 500)
    private String textContent;

    /** Publicly accessible URL of the announcement image. */
    @Column(name = "image_url", length = 500)
    private String imageUrl;

    /**
     * Auto-detected orientation of the image: LANDSCAPE if width &gt; height, PORTRAIT otherwise.
     * Null when no image is attached.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "image_orientation", length = 20)
    private ImageOrientation imageOrientation;

    /** Optional URL the user is redirected to when clicking the announcement. */
    @Column(name = "redirect_url", length = 500)
    private String redirectUrl;

    /** Display position in the carousel (0 = first). Lower values appear first. */
    @Column(name = "sort_order", nullable = false)
    private int sortOrder = 0;

    /** Whether this announcement is currently shown on the home page. */
    @Column(nullable = false)
    private boolean active = true;

    /** Timestamp when this announcement was created. */
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    /** Timestamp when this announcement was last modified. */
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    /** @return the announcement UUID */
    public UUID getId() { return id; }

    /** @return the owning vendor account */
    public Account getVendor() { return vendor; }

    /** @param vendor the owning vendor account */
    public void setVendor(Account vendor) { this.vendor = vendor; }

    /** @return the content type */
    public AnnouncementContentType getContentType() { return contentType; }

    /** @param contentType the content type */
    public void setContentType(AnnouncementContentType contentType) { this.contentType = contentType; }

    /** @return the text content, or null if this is an image-only announcement */
    public String getTextContent() { return textContent; }

    /** @param textContent the text content */
    public void setTextContent(String textContent) { this.textContent = textContent; }

    /** @return the image URL, or null if this is a text-only announcement */
    public String getImageUrl() { return imageUrl; }

    /** @param imageUrl the image URL */
    public void setImageUrl(String imageUrl) { this.imageUrl = imageUrl; }

    /** @return the auto-detected image orientation, or null when no image is present */
    public ImageOrientation getImageOrientation() { return imageOrientation; }

    /** @param imageOrientation the computed image orientation */
    public void setImageOrientation(ImageOrientation imageOrientation) { this.imageOrientation = imageOrientation; }

    /** @return the optional redirect URL */
    public String getRedirectUrl() { return redirectUrl; }

    /** @param redirectUrl the optional redirect URL */
    public void setRedirectUrl(String redirectUrl) { this.redirectUrl = redirectUrl; }

    /** @return the display sort order */
    public int getSortOrder() { return sortOrder; }

    /** @param sortOrder the display sort order */
    public void setSortOrder(int sortOrder) { this.sortOrder = sortOrder; }

    /** @return true if this announcement is currently visible on the home page */
    public boolean isActive() { return active; }

    /** @param active true to show this announcement in the carousel */
    public void setActive(boolean active) { this.active = active; }

    /** @return the creation timestamp */
    public LocalDateTime getCreatedAt() { return createdAt; }

    /** @param createdAt the creation timestamp */
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }

    /** @return the last-modified timestamp */
    public LocalDateTime getUpdatedAt() { return updatedAt; }

    /** @param updatedAt the last-modified timestamp */
    public void setUpdatedAt(LocalDateTime updatedAt) { this.updatedAt = updatedAt; }
}
